### ISSUE TITLE
Problem with autorizetion if systemd-swap startup

### ISSUE THREAD

**Issue by JesterMEV** [Nefelim4ag/systemd-swap#161]
If systemd-swap start is enabled then
![изображение](https://user-images.githubusercontent.com/32267296/87421931-2c585c80-c5f1-11ea-8983-12ea292fd87c.png)
if you disable it everything is fine
distribution arch linux  dm gdm

**Comment by Jarel1337** [comment]
Did this happen on 4.2.3? Is there a systemd-swap error message?

**Comment by JesterMEV** [comment]
after the last update 
![изображение](https://user-images.githubusercontent.com/32267296/87449476-b2d36500-c616-11ea-9b70-9c117e406f1c.png)

**Comment by leogx9r** [comment]
I also noticed this happening as well and `systemd-swap.service` definitely seems to be causing it. I've tested on the following kernels:

- 5.7.7
- 5.7.8
- 5.7.9

The kernel actually takes around 40 seconds to initialize the allocated zram segments based on some brief debugging which causes other services to hang until it does, in my case, the entire desktop.

I guess either a3c652b or 005fed4 would be the cause but unfortunately I can't test since I do need my system up and running and I already spent a few hours diagnosing this already.

**Comment by JesterMEV** [comment]
@leogx9r +1 when starting system-swap
![Снимок экрана от 2020-07-17 06-13-52](https://user-images.githubusercontent.com/32267296/87740351-6d23c180-c7fb-11ea-8403-aada90c9ef43.png)
if without systemd-swap and with another service for zram zramswap.service
![изображение](https://user-images.githubusercontent.com/32267296/87740640-1e2a5c00-c7fc-11ea-97db-cd188534f680.png)

**Comment by Jarel1337** [comment]
Can you guys remove the realtime property of systemd-swap? (Delete `CPUSchedulingPolicy=fifo` in systemd-swap.service)

**Comment by JesterMEV** [comment]
![изображение](https://user-images.githubusercontent.com/32267296/87754470-6bb7c080-c81e-11ea-885c-57378bbc9022.png)
nоt help

**Comment by Jarel1337** [comment]
Could you see if reverting 8f120caffda8dc36992a78679fac2b104319fcab fixes it? (The for-loop)

**Comment by JesterMEV** [comment]
@Jarel1337 it's work fine thx

**Comment by JesterMEV** [comment]
![изображение](https://user-images.githubusercontent.com/32267296/87852215-86bb2b00-c919-11ea-9412-c689840671d9.png)
8f120ca
snope 0.2 
causes the error in the screenshot again
snope 1
work fine

**Comment by Jarel1337** [comment]
@JesterMEV does snore 0.5 fix it?

**Comment by JesterMEV** [comment]
@Jarel1337 0.9 work
