### ISSUE TITLE
Hibernate / resume from loopback swapfile

### ISSUE THREAD

**Issue by HaleTom** [Nefelim4ag/systemd-swap#33]
I'm using `btrfs`, so my swapfile needs to be loopback mounted.

Is there a way of having a persistent loopback `/dev/<DEVICE>` so that I can pass `resume=` in my kernel parameters and have it resume from the loopback device?

**Comment by Nefelim4ag** [comment]
It's not possible with systemd-swap, because systemd-swap create swap in a way like O_TMPFILE.
---
For persistent loop back device you must try modify your initrd image in way like:
mount fs with file RO
create loopback device
load data from it to kernel interface by some way (i forget how to do it manualy)
