### ISSUE TITLE
First chunk is not created without a swapfile.

### ISSUE THREAD

**Issue by osteichthyes** [Nefelim4ag/systemd-swap#37]
I raised a bug in arch, but this may be easier here.

Here's the bug report:
Description:
Because the chunk generation is triggered by the swap falling below 15% (or whatever is configured in the config), a system with no other swap will always have 0% full, so the first chunks is never created. I worked around this by simply creating a small swap file (~10M), which is trivial from a swapping standpoint, but that way when it is <15% empty, the first chunk is generated. You could easily add a similar function to systemd-swap, to allocate a 10M swapfile, further, it could be a simple config option so folks with an actual swap partition could skip it.

**Comment by Nefelim4ag** [comment]
@osteichthyes, can you reproduce this bug?
Because i can't
https://github.com/Nefelim4ag/systemd-swap/blob/master/systemd-swap#L178
```
get_free_swap_perc(){
                    # +1 prevent devide by zero
                    total="$(grep SwapTotal: /proc/meminfo | grep -o -e '[0-9]*')"
                    free="$(grep SwapFree: /proc/meminfo | grep -o -e '[0-9]*')"
                    total=$((total*1024))
                    free=$((free*1024))
                    echo $(( (${free}*100)/(${total}+1) ));
            }
```
If free = 0 && total = 0, then function return 0/1 = 0, then
https://github.com/Nefelim4ag/systemd-swap/blob/master/systemd-swap#L215
if (( $curr_free_swap_perc < $free_swap_perc )) && (( allocated < max_count )); then
0 is less then $free_swap_perc and allocated = 0 i.e. < max_count

So chunk will be created and i test it without other swaps, it's working as expected

**Comment by osteichthyes** [comment]
I thought it was a feature request, not a bug. Anyway, I only got it on a raspberry pi and realized that with that little processing power, it was easier to just pre-allocate the swap. Sorry, I should have tested better/looked at the code before raising a bug.
