### ISSUE TITLE
upstream to systemd

### ISSUE THREAD

**Issue by adrelanos** [Nefelim4ag/systemd-swap#50]
Do you think you could upstream this to systemd?

Advantages:

* more popularity / oversight
* available in all distributions by default

**Comment by Nefelim4ag** [comment]
@adrelanos,
https://lists.freedesktop.org/archives/systemd-devel/2017-February/038333.html

**Comment by adrelanos** [comment]
Thanks! Makes sense!

**Comment by w-flo** [comment]
After seeing this issue, I believe this project's name and the configuration file path is a little misleading. I saw the package mentioned on the Arch Wiki and simply wanted a swap file, so this looked like the quickest way and I installed the package, assuming that it's part of systemd / made according to their standards since they call their tools systemd-* and the config is in /etc/systemd/.

Later I noticed that something had started to fork new processes all the time and there's a "sleep 1" process constantly running, which is something that makes me feel weird. :-) When I saw that it's systemd-swap that does this, I couldn't believe it because it's not something I expect systemd tools to do, they're usually rather lightweight and coded and C, and don't do heavy things like fork all the time for something that appears like an easy task, like swap management. So I looked into this a little more and quickly realized that systemd-swap is not really part of systemd, which explains why it appears to be a little more wasteful when using system ressources compared to systemd tools.

Anyway, the scripts worked flawlessly for me, so let me give you a big thank you. Still, I prefer any system tools that wake up often and do some work not to be bash scripts, so I removed the package from the system. I probably would not have installed it if I knew that it wasn't a systemd tool and chosen a swap unit instead. It's obviously my own fault for making false assumptions based on the package name, just wanted to let you know about my experience. :-)
