### ISSUE TITLE
Memory corruption with swapfc

### ISSUE THREAD

**Issue by ypnos** [Nefelim4ag/systemd-swap#53]
Using swapfc and some processes that are high load on both CPU and RAM, the following situation arose:
1. Swap files are activated
2. Swap files are deactivated, but takes too long, systemd kills swap deactivation due to timeout

Result: Memory corruption on running processes, including two virtual machines, their kernels then crashed.

Please see the [host journal excerpt](https://github.com/Nefelim4ag/systemd-swap/files/1789437/swapfail.log).

I configured swapfc with settings:
```
swapfc_enabled=1
swapfc_force_use_loop=0     # Force usage of swapfile + loop
swapfc_frequency=1s         # How often check free swap space
swapfc_chunk_size=1024M     # Allocate size of swap chunk
swapfc_max_count=32         # 0 - unlimited, note: 32 is a kernel maximum
swapfc_free_swap_perc=15    # Add new chunk if free < 15%
                            # Remove chunk if free > 15+40% & chunk count > 2
swapfc_path=/var/lib/systemd-swap/swapfc/
# Only for swapfile + loop
swapfc_nocow=1              # Disable CoW on swapfile
swapfc_directio=1           # Use directio for loop dev
swapfc_force_preallocated=0 # Will preallocate created files
```
Is this a problem of systemd-swap and/or could it be avoided?

**Comment by Nefelim4ag** [comment]
@ypnos, i'm very unsure what shell can lead to memory corruption.

But if you want, you can try that:
https://github.com/Nefelim4ag/systemd-swap/commit/7fe5d882cc257f48d53123f2dbedcf25ca720dfd

**Comment by ypnos** [comment]
Thank you for the patch. I think it makes sense given the notoriety of swapoff for being slow as hell.

I can't tell what happened that night, only thing I see is that swapoff was killed prematurely.
Does it have an effect on the swapoff syscall? I don't know. Or was it a problem that the same file was been activated afterwards again?

All I see is that QEMU did not crash, the guest systems crashed. Because their memory was mapped with virtio, who knows who actually owned the memory at that point.

**Comment by Nefelim4ag** [comment]
@ypnos, i didn't see in your log that systemd-swap do things like:
free N
create N

May be i bad at reading log carefully.
In that condition - yes, that can happened and memory stored at swapfile will be corrupted.
But in that case (IMHO), it's very likely to whole system hangs/kernel panic, not just crash at vm.

AFAIK swapoff are kill safe, because on it's self it do nothing.

So i just luck of ideas why that happens, and what funny i use:
~# systemctl stop <dev>.swap
Because i assume it's must be safe and smart %).

Also i never try memory mapping in qemu, so can't say anything.

**Comment by ypnos** [comment]
I think we can close this issue, I am not able to reproduce this.
Thank you very much for your great work and your consideration!
